<?php
/**
 * BitLoop / Google Tag Manager / Block / Script
 * @see BitLoop_GoogleTagManager_Block_Script
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2015 BitLoop Limited (www.bitloop.co.uk)
 * @license     BitLoop License
 */
?>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','<?php echo $this->getContainerId(); ?>');</script>
<!-- End Google Tag Manager -->
